server:
  port: 8073
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/pages/
      suffix: .jsp
  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studenthelp?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
dubbo:
  scan:
    basePackages: com.student
  application:
    name: consumer-student-web #服务名称唯一
  registry:
    address: zookeeper://192.168.77.129:2181?backup=192.168.77.129:2182,192.168.77.129:2183
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.student.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.student.mapper: debug

  